name: Deploy README.md
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches:
      - "feat/generate" # This is just for testing

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.5"
      - run: poetry run python scripts/generate_readme.py
      - name: Commit report
        run: |
          git config --global user.name 'Tsung-Ju Lii'
          git config --global user.email 'usefulalgorithm@users.noreply.github.com'
          git commit -am "Update README (${date +"%Y-%m-%d})"
          git push
            